export const bills = [
  {
    id: 1,
    billNumber: "2023000206",
    accountNumber: "094000001",
    paymentDueDate: "",
    mapNumber: "717265A003",
    location: "688 JEFF HENDRICKS ROAD",
    totalDueAmount: "",
    title: "",
    di: "",
    payments: "",
    otherCharges: "",
    parcel: "",
    decal: "",
    fairMarketValue: "",
    origination: {
      name: "",
      town: "",
      address: "",
      number: "",
      pobox: "",
    },
    destination: {
      name: "SMITH FRANKLIN R",
      town: "C/O SHONDA OWENS",
      address: "WOODLAND, GA 31836",
      number: "",
      pobox: "",
    },
    billableItem: {
      name: "",
      billableItemDescription: {
        year: "",
        manufacturer: "",
        model: "",
        street: "",
        mfgId: "",
      },
    },
    billItems: {
      assessement: "",
      mhValue: "",
      decks: "",
      utility: "",
    },
    taxEntity: {
      county: {
        milleageRate: "",
        taxDue: "",
      },
      school: {
        milleageRate: "",
        taxDue: "",
      },
      garbage: {
        milleageRate: "",
        taxDue: "",
      },
    },
  },
  {
    id: 2,
    billNumber: "",
    accountNumber: "",
    paymentDueDate: "",
    mapNumber: "",
    location: "",
    totalDueAmount: "",
    title: "",
    di: "",
    payments: "",
    otherCharges: "",
    parcel: "",
    decal: "",
    fairMarketValue: "",
    origination: {
      name: "",
      town: "",
      address: "",
      number: "",
      pobox: "",
    },
    destination: {
      name: "SASHA MARLEY",
      town: "C/O LINENS OWENS",
      address: "OAKLAND, GA#44",
      number: "",
      pobox: "",
    },
    billableItem: {
      name: "",
      billableItemDescription: {
        year: "",
        manufacturer: "",
        model: "",
        street: "",
        mfgId: "",
      },
    },
    billItems: {
      assessement: "",
      mhValue: "",
      decks: "",
      utility: "",
    },
    taxEntity: {
      county: {
        milleageRate: "",
        taxDue: "",
      },
      school: {
        milleageRate: "",
        taxDue: "",
      },
      garbage: {
        milleageRate: "",
        taxDue: "",
      },
    },
  },
]
